env:
    # RECOVERY REPOSITORY SOURCE TWRP,PBRP,SHRP
    MANIFEST: --depth=1 -u https://github.com/PitchBlackRecoveryProject/manifest_pb

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[505fba0254f594f7fb60e2b068a72f7c15774cc4e08504512f2acb437037cc6a92adfd8fff9f5030f6debe4b4cc4f24f]
    TG_TOKEN: ENCRYPTED[56ec524335ba69413c50889513cea95ea5ac1cc90532318d81d9c10057db4b1d3dbcfc4b315da52414c6862bcb08e256]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 20G

  Checks_script:
      - curl -sL https://raw.githubusercontent.com/GunjanSkry/pbrp_ci/main/scripts/checks.sh | bash

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/GunjanSkry/pbrp_ci/main/scripts/sync.sh | bash

  Build_script:
      - curl -sL https://raw.githubusercontent.com/GunjanSkry/pbrp_ci/main/scripts/build.sh | bash

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - curl https://raw.githubusercontent.com/GunjanSkry/pbrp_ci/main/scripts/upload.sh | bash
